//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.08 at 09:15:46 PM PDT 
//


package tosc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Alternative complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Alternative">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}object"/>
 *         &lt;element name="label" type="{}Tags"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Alternative", propOrder = {
    "object",
    "label"
})
public class Alternative {

    @XmlElementRef(name = "object", type = JAXBElement.class)
    protected JAXBElement<?> object;
    @XmlElement(required = true)
    protected Tags label;

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Variable }{@code >}
     *     {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link Choice }{@code >}
     *     {@link JAXBElement }{@code <}{@link Part }{@code >}
     *     {@link JAXBElement }{@code <}{@link Let }{@code >}
     *     
     */
    public JAXBElement<?> getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Variable }{@code >}
     *     {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link Choice }{@code >}
     *     {@link JAXBElement }{@code <}{@link Part }{@code >}
     *     {@link JAXBElement }{@code <}{@link Let }{@code >}
     *     
     */
    public void setObject(JAXBElement<?> value) {
        this.object = ((JAXBElement<?> ) value);
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Tags }
     *     
     */
    public Tags getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tags }
     *     
     */
    public void setLabel(Tags value) {
        this.label = value;
    }

}
